version: '2'
services:
  ethereum:
    image: "parity/parity:latest"
    restart: always
    container_name: "parity-${CHAIN}"
    working_dir: /parity/
    command: "--chain ${CHAIN} --jsonrpc-interface all --ws-interface all --ws-origins all --no-warp"
    volumes:
      - "$HOME/.parity/share/io.parity.ethereum/docker/${CHAIN}/:/root/.local/share/io.parity.ethereum/"
    ports:
      # - 8180:8180
      - 8545:8545
      - 8546:8546
      # - 30303:30303
      # - 30303:30303/udp

  indexer:
    image: "tradle/eth-indexer"
    restart: always
    container_name: "eth-indexer-${CHAIN}"
    volumes:
      - "$HOME/.eth-indexer/${CHAIN}/:/root/.eth-indexer/"
    environment:
      NODE_NETWORK: "${CHAIN}"
      NODE_HOST: 'ethereum'
      DEBUG: 'tradle:*'
      START_BLOCK: 0
      CONFIRMATION_HEIGHT: 15
    ports:
      - 9898:9898
