version: '2'
services:
  redis:
    image: redis:alpine
    container_name: "redis-parity-${CHAIN}"
    ports:
      - 6380:6379
    volumes:
      - "${HOME}/.parity/redis-${CHAIN}:/data"

  parity:
    image: "parity/parity:stable"
    restart: always
    container_name: "parity-${CHAIN}"
    working_dir: /parity/
    # see parity-settings.png
    command: "--chain ${CHAIN} --jsonrpc-interface all --ws-interface all --ws-origins all --no-warp"
    volumes:
      - "$HOME/.parity/share/io.parity.ethereum/docker/${CHAIN}:/root/.local/share/io.parity.ethereum/"
    ports:
      # - 8180:8180
      - 8545:8545
      - 8546:8546
      # - 30303:30303
      # - 30303:30303/udp
